[app]
# spring application root directory.  The application will look at src/main/resources for configuration files
project_root = "<project-root-directory>"

# directory that holds external configuration files
external_properties = "external-property-directory"