[[constraint]]
  name = "github.com/manifoldco/promptui"
  version = "0.7.0"

[[override]]
  name = "github.com/chzyer/readline"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.6.2"

[prune]
  go-tests = true
  unused-packages = true
